### PR TITLE
EnvironmentFile

### PR DESCRIPTION
**Pull request by kevit**

### CODE REVIEW

**Comment by kevit** [comment]
sorry I was wrong here

**Comment by nozpheratu** [comment]
Actually I could use this commit. Multiple instances are created from my systemd services and the single default EnvironmentFile that gets generated based on the service name is not adequate for me.

However, I think the desired logic should be something more along the lines of:
```j2
{% if systemd_service_Service_EnvironmentFile is defined %}
EnvironmentFile={{ systemd_service_Service_EnvironmentFile }}
{% else %}
EnvironmentFile=-{{ systemd_service_default_dir }}/{{ systemd_service_name }}
{% endif -%}
```

**Comment by kevit** [comment]
I like your way as it is, I just had a wrong idea about the common shared env file. It looks more logical if I will fill environment per service.

**Comment by nozpheratu** [comment]
@kevit But it doesn't really fulfill that goal if a systemd service run multiple instances since it will use the same Environment file for all of them. Being able to specify the path to the environment file gives it a bit more flexibility.

**Pull request closed without merging**
