### PR TITLE
corrects ExecStop in the Service section

### PR DESCRIPTION
**Pull request by johngoldfinger**
This looks like a typo ... the original code is not a valid systemd tag

### CODE REVIEW

**Comment by talset** [comment]
+1 it looks like a typo.

And I think this is the same for

*  https://github.com/tumf/ansible-role-systemd-service/blob/master/templates/service.j2#L85
*  https://github.com/tumf/ansible-role-systemd-service/blob/master/templates/service.j2#L97

Could you fix those too ?

Thanks @johngoldfinger

**Comment by talset** [comment]
Why did you closed this PR @johngoldfinger ?

I think it need to be merged.

**Comment by johngoldfinger** [comment]
Apologies, I'm not very familiar with the process. Do I need to reopen it?

**Comment by talset** [comment]
@johngoldfinger yes please, reopen it if you are able.

@tumf could you have a look and merge in order to fix this issue :

```
Mar 08 10:25:23 kubernetes-test-master0 systemd[1]: [/etc/systemd/system/kubelet.service:11] Unknown lvalue 'Service_ExecStop' in section 'Service'
```

Thanks guys

**Review by tumf — APPROVED** [review]

**Pull request merged**
